manifest:
  remotes:
    - name: zmk-config-zen-2
      url-base: https://github.com/sumtsui
  projects:
    - name: zmk
      remote: zmk-config-zen-2
      revision: main  # custom branch name
      import: app/west.yml
  self:
    path: config