manifest:
  remotes:
    - name: sumtsui
      url-base: https://github.com/sumtsui
  projects:
    - name: zmk-config-zen-2 # repo name
      remote: sumtsui
      revision: main  # custom branch name
      import: app/west.yml
  self:
    path: config